name: TypeScript Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run on LTS version
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          SCHOOL_USERNAME: ${{ secrets.SCHOOL_USERNAME }}
          SCHOOL_PASSWORD: ${{ secrets.SCHOOL_PASSWORD }}
          SCHOOL: ${{ secrets.SCHOOL }}
      - run: |
          touch .env
          echo SCHOOL=${{ secrets.SCHOOL }} >> .env
          echo SCHOOL_USERNAME=${{ secrets.SCHOOL_USERNAME }} >> .env
          echo SCHOOL_PASSWORD=${{ secrets.SCHOOL_PASSWORD }} >> .env
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: rm .env